version: 0.2

phases:
  install:
    commands:
      - echo Installing Nginx
      - sudo apt-get update -y
      - sudo apt-get install nginx -y

  build:
    commands: 
      - echo Building app
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring Nginx

artifacts:
  files:
    - /var/www/html/index.html